etcd-io/dbtester

- control/config.go
- control/control.go
> control: reduce some code duplication 

- control/control.go
- control/io.go
- control/util.go
> control: refactor away some duplicated code, untangle some of step2

- control/control.go
- control/util.go
> control: add read-oneshot read benchmark

- glide.lock
- glide.yaml
- vendor/github.com/biogo/graphics/bezier/bezier.go
- vendor/github.com/gonum/plot/axis.go
- vendor/github.com/gonum/plot/plotter/heat.go
- vendor/github.com/gonum/plot/plotter/sankey.go
- vendor/github.com/hashicorp/consul/api/kv.go
- vendor/github.com/hashicorp/consul/api/lock.go
- vendor/github.com/hashicorp/consul/api/snapshot.go
- vendor/github.com/samuel/go-zookeeper/zk/lock.go
and sync with 'gonum/plot' master
> *: clean up vendor, sync with consul, zk client master

- control/report.go
Facing some issues with Zk tests hanging in finializing benchmark data
> control: add more debugging logs

- agent/agent.go
- bench-configuration/01-write-2M-keys/04-zetcd-etcd-v3.1.yaml
- bench-configuration/01-write-2M-keys/05-cetcd-etcd-v3.1.yaml
- control/config.go
- control/control.go
- control/test.yaml
For https://github.com/coreos/dbtester/issues/31.
> agent: handle 'zetcd', 'cetcd' database request

- agent/agent.go
> agent: use localhost for cetcd, zetcd

- bench-configuration/01-write-2M-keys/01-zk-r3.4.9.yaml
- bench-configuration/01-write-2M-keys/02-etcd-v3.1.yaml
- bench-configuration/01-write-2M-keys/03-consul-v0.7.2.yaml
- bench-configuration/01-write-2M-keys/04-zetcd-v3.1.yaml
- bench-configuration/01-write-2M-keys/05-cetcd-v3.1.yaml
- bench-configuration/01-write-2M-keys/analyze.yaml
- bench-configuration/02-read-2M-keys-linearizable/01-zk-r3.4.9.yaml
- bench-configuration/02-read-2M-keys-linearizable/02-etcd-v3.1.yaml
- bench-configuration/02-read-2M-keys-linearizable/03-consul-v0.7.2.yaml
- bench-configuration/02-read-2M-keys-linearizable/04-zetcd-v3.1.yaml
- bench-configuration/02-read-2M-keys-linearizable/05-cetcd-v3.1.yaml
- bench-configuration/02-read-2M-keys-linearizable/analyze.yaml
- control/config.go
- control/config_test.go
- control/control.go
- control/test.yaml
- glide.lock
- glide.yaml
- vendor/github.com/prometheus/common/model/metric.go
- vendor/golang.org/x/image/font/font.go
- vendor/golang.org/x/time/LICENSE
- vendor/golang.org/x/time/PATENTS
- vendor/golang.org/x/time/rate/rate.go
Fix https://github.com/coreos/dbtester/issues/112.
> control: support rate-limit

- analyze/analyze_config.go
- analyze/analyze_config.yaml
- analyze/analyze_config_test.go
- analyze/analyze_final.go
- bench-configuration/01-write-2M-keys/analyze.yaml
- glide.lock
- glide.yaml
- vendor/github.com/gyuho/dataframe/dataframe.go
Fix https://github.com/coreos/dbtester/issues/132.
> *: save CSV for each plot

- control/step2_stress_database.go
Fix https://github.com/coreos/dbtester/issues/140.
> control: use NewReportSample

- bench-configuration/01-write/02-zookeeper-r3.4.9.yaml
- bench-configuration/01-write/03-consul-v0.7.2.yaml
Fix https://github.com/coreos/dbtester/issues/150.
> bench-configuration: fix client panic (wrong config)

- control/step2_stress_database.go
Fix https://github.com/coreos/dbtester/issues/150.
> control: fix shawdowed write handler

- control/step2_stress_database.go
Fix https://github.com/coreos/dbtester/issues/150.
> control: fix connection number (same as clients)

- control/step2_stress_database.go
- vendor/github.com/coreos/etcd/pkg/report/report.go
Fix https://github.com/coreos/dbtester/issues/159.
> pkg/report: revert to etcd master, fix zk control

- control/step2_stress_database.go
It was printing out etcd gcloud key...
> control: remove log

- bench-configuration/01-write/01-etcd-v3.1.yaml
- bench-configuration/01-write/02-zookeeper-r3.4.9.yaml
- bench-configuration/01-write/03-consul-v0.7.2.yaml
- control/config_test.go
- control/config_test.yaml
- control/step2_stress_database.go
- control/step2_stress_database_test.go
Fix https://github.com/coreos/dbtester/issues/155.
> *: add 5-connection, round-off 10k digits, separate reports in control

- analyze/analyze_data_4_aggregate_all.go
- analyze/analyze_final.go
- bench-configuration/00-write-2M-keys/01-etcd-v3.1.yaml
- bench-configuration/00-write-2M-keys/02-zookeeper-r3.4.9.yaml
- bench-configuration/00-write-2M-keys/03-consul-v0.7.2.yaml
- bench-configuration/00-write-2M-keys/analyze.yaml
- bench-configuration/01-write/01-etcd-v3.1.yaml
- bench-configuration/01-write/02-zookeeper-r3.4.9.yaml
- bench-configuration/01-write/03-consul-v0.7.2.yaml
- bench-configuration/01-write/analyze.yaml
- bench-configuration/read-2M-keys-linearizable/01-etcd-v3.1.yaml
- bench-configuration/read-2M-keys-linearizable/02-zookeeper-r3.4.9.yaml
- bench-configuration/read-2M-keys-linearizable/03-consul-v0.7.2.yaml
- control/step2_stress_database.go
Fix https://github.com/coreos/dbtester/issues/175.
> *: add control client num

- control/step2_stress_database.go
Fix https://github.com/coreos/dbtester/issues/175
> control: fix clientN tracking

- analyze/analyze_final.go
Fix https://github.com/coreos/dbtester/issues/182.
> analyze: aggregate data by client-num

- README.md
- analyze/analyze_data_3_benchmark_metrics.go
- bench-configuration/02-write-1M-keys-rate-limited/analyze.yaml
- bench-configuration/03-write-1M-keys-client-variable/analyze.yaml
- bench-configuration/05-write-1M-keys-rate-limited/analyze.yaml
- bench-configuration/06-write-1M-keys-client-variable/analyze.yaml
Fix https://github.com/coreos/dbtester/issues/202.
> *: add results with bare metal machines

- pkg/fileinspect/fileinspect.go
- pkg/fileinspect/fileinspect_test.go
For https://github.com/coreos/dbtester/issues/221
> pkg/fileinspect: add dir size utils

- analyze/analyze_config.go
- analyze/analyze_config.yaml
- analyze/analyze_config_test.go
- analyze/analyze_data_7_finalize_everything.go
- bench-configuration/01-write-1M-keys-client-variable/analyze.yaml
- bench-configuration/02-write-1M-keys-best-throughput/analyze.yaml
- bench-configuration/03-write-1M-keys-1000-client/analyze.yaml
- bench-configuration/04-write-too-many-keys/analyze.yaml
- control/command.go
For https://github.com/coreos/dbtester/issues/221.
> analyze: print data size summary

- analyze/analyze_data_4_aggregate_all.go
Fix https://github.com/coreos/dbtester/issues/224.
> analyze: fix 'CUMULATIVE-THROUGHPUT'

- glide.lock
- glide.yaml
- vendor/github.com/gyuho/psn/proc_csv_interpolate.go
Fix https://github.com/coreos/dbtester/issues/247.
> vendor: fix wrong interpolation in 'psn'

- bench-configuration/01-write-1M-keys-client-variable/01-etcd-v3.1.yaml
- bench-configuration/01-write-1M-keys-client-variable/02-zookeeper-r3.4.9.yaml
- bench-configuration/01-write-1M-keys-client-variable/03-consul-v0.7.3.yaml
- bench-configuration/02-write-1M-keys-best-throughput/01-etcd-v3.1.yaml
- bench-configuration/02-write-1M-keys-best-throughput/02-zookeeper-r3.4.9.yaml
- bench-configuration/02-write-1M-keys-best-throughput/03-consul-v0.7.3.yaml
- bench-configuration/03-write-1M-keys-1000-client/01-etcd-v3.1.yaml
- bench-configuration/03-write-1M-keys-1000-client/02-zookeeper-r3.4.9.yaml
- bench-configuration/03-write-1M-keys-1000-client/03-consul-v0.7.3.yaml
- bench-configuration/04-write-too-many-keys/01-etcd-v3.1.yaml
- bench-configuration/04-write-too-many-keys/02-zookeeper-r3.4.9.yaml
- bench-configuration/04-write-too-many-keys/03-consul-v0.7.3.yaml
- control/command.go
- control/config.go
- control/config_test.go
- control/config_test.yaml
- control/step4_upload_logs.go
Fix https://github.com/coreos/dbtester/issues/252.
> control: collect system metrics in client side

- README.md
- analyze/analyze_data_5_plot.go
- analyze/analyze_data_7_finalize_everything.go
- bench-configuration/01-write-1M-keys-client-variable/analyze.yaml
- bench-configuration/02-write-1M-keys-best-throughput/analyze.yaml
- bench-configuration/03-write-1M-keys-1000-client/analyze.yaml
- bench-configuration/04-write-too-many-keys/analyze.yaml
- bench-results/2017Q1-02-etcd-zookeeper-consul/README.md
For https://github.com/coreos/dbtester/issues/221.
> *: new results with min/max

- analyze/analyze_config.go
- analyze/analyze_config.yaml
- analyze/analyze_config_test.go
- analyze/analyze_data_7_finalize_everything.go
- bench-configuration/01-write-1M-keys-client-variable/analyze.yaml
- bench-configuration/02-write-1M-keys-best-throughput/analyze.yaml
- bench-configuration/03-write-1M-keys-1000-client/analyze.yaml
- bench-configuration/04-write-too-many-keys/analyze.yaml
- glide.lock
- glide.yaml
- vendor/github.com/gyuho/psn/proc_csv_interpolate.go
For https://github.com/coreos/dbtester/issues/221.
> analyze: display client machine results, psn: fix uint64 overflow with negative delta

- bench-configuration/02-write-1M-keys-best-throughput/01-etcd-v3.1.yaml
- bench-configuration/02-write-1M-keys-best-throughput/02-zookeeper-r3.4.9.yaml
- bench-configuration/02-write-1M-keys-best-throughput/03-consul-v0.7.3.yaml
- bench-configuration/02-write-1M-keys-best-throughput/analyze.yaml
- bench-configuration/04-write-too-many-keys/01-etcd-v3.1.yaml
- bench-configuration/04-write-too-many-keys/02-zookeeper-r3.4.9.yaml
- bench-configuration/04-write-too-many-keys/03-consul-v0.7.3.yaml
- bench-configuration/04-write-too-many-keys/analyze.yaml
For https://github.com/coreos/dbtester/issues/221
> bench-configuration: config with best throughput

- glide.lock
- glide.yaml
- vendor/github.com/gonum/floats/floats.go
- vendor/github.com/gyuho/psn/generated_linux.go
- vendor/github.com/gyuho/psn/proc_diskstat_linux.go
- vendor/github.com/gyuho/psn/schema/schema.go
Fix https://github.com/coreos/dbtester/issues/249.
> *: update 'psn' to fix sector writes issue

- analyze/04_aggregate_all_analyze_data.go
- config_dbtester_test.go
- config_dbtester_test.yaml
- test-configs/01-write-1M-keys-client-variable.yaml
- test-configs/02-write-1M-keys-best-throughput.yaml
- test-configs/03-write-too-many-keys.yaml
Fix https://github.com/coreos/dbtester/issues/289
> *: add 'MAX-CPU'

- analyze/05_plot.go
- config_dbtester.go
- stress.go
Fix https://github.com/coreos/dbtester/issues/293
> *: add 'etcdtip' as database ID

- control/command.go
- dbtesterpb/util.go
Fix https://github.com/coreos/dbtester/issues/312.
> *: add default value to 'database-id'

- glide.lock
- glide.yaml
- test-configs/01-write-1M-keys-client-variable.yaml
- test-configs/02-write-1M-keys-best-throughput.yaml
- test-configs/03-write-too-many-keys.yaml
- test-configs/install-etcd.sh
- vendor/github.com/coreos/etcd/clientv3/balancer.go
- vendor/github.com/coreos/etcd/clientv3/client.go
- vendor/github.com/coreos/etcd/clientv3/watch.go
- vendor/github.com/hashicorp/consul/api/operator.go
> *: sync with etcd, Consul master

- test-configs/01-write-1M-keys-client-variable.yaml
- test-configs/02-write-1M-keys-best-throughput.yaml
- test-configs/03-write-too-many-keys.yaml
- test-configs/install-etcd.sh
- test-configs/install-go.sh
> test-configs: update google storage bucket name, other updates

- test-configs/01-write-1M-keys-client-variable.yaml
- test-configs/02-write-1M-keys-best-throughput.yaml
- test-configs/03-write-too-many-keys.yaml
> test-configs: specify Linux kernel version

- stress.go
> stress: fix database ID, add more panic-logs

- test-configs/01-write-1M-keys-client-variable.yaml
- test-configs/02-write-1M-keys-best-throughput.yaml
- test-configs/03-write-too-many-keys.yaml
> test-configs: revert bucket name change

- agent/server.go
> agent: fix unknown databae ID issue for zookeeper

- agent/agent_zookeeper.go
Fix https://github.com/coreos/dbtester/issues/323.
> agent: fix jvm flag order

- test-configs/01-write-1M-keys-client-variable.yaml
- test-configs/02-write-1M-keys-best-throughput.yaml
- test-configs/03-write-too-many-keys.yaml
> test-configs: mention 'ulimit -n'

- agent/agent_zookeeper.go
> agent: fix jvm experimental flags

- agent/agent_zookeeper.go
> agent: fix

- test-results/2017Q1-01-etcd-zookeeper-consul/README.md
Fix https://github.com/coreos/dbtester/issues/309.
> test-results: new data with jvm flags

- README.md
> README: use new data

- dbtesterpb/util.go
> dbtesterpb: use 'cyan' color for etcd v3.1

- agent/server.go
Fix https://github.com/coreos/dbtester/issues/330.
> agent: workaround for java kill

- test-configs/01-write-1M-keys-client-variable.yaml
- test-configs/02-write-1M-keys-best-throughput.yaml
- test-configs/03-write-too-many-keys.yaml
- test-configs/04-write-1M-keys-1000QPS.yaml
> test-configs: clarify CPU average, maximum

- README.md
- vendor/github.com/golang/freetype/licenses/ftl.txt
- vendor/github.com/golang/freetype/licenses/gpl.txt
Add the text for freetype licenses.
> Add freetype licenses
